version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    working_dir: /usr/src/app
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
#      - /usr/src/app/node_modules
    restart: unless-stopped

  postgres:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - nesjs-network

  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 63791:6379
    volumes:
      - ./redis:/data
    restart: always
    networks:
      - nesjs-network

#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: 'rabbitmq'
#    ports:
#      - 5672:5672
#      - 15672:15672
#    volumes:
#      - ./rabbitmq/data/:/var/lib/rabbitmq/
#      - ./rabbitmq/log/:/var/log/rabbitmq
#    networks:
#      - nesjs-network

networks:
  nesjs-network:
##    driver: bridge
##  postgres:
##    driver: bridge
#
#volumes:
#  db:
#    driver: local
#    external: true

#volumes:
#  pgdata: